name: smard_nuclear
version: "1.0.0"
config-version: 2

profile: smard_nuclear

model-paths:  ["models"]
seed-paths:   ["seeds"]
macro-paths:  ["macros"]

target-path:  "target"
clean-targets: ["target", "dbt_packages"]

models:
  smard_nuclear:
    staging:
      +materialized: view
      +schema: staging

    marts:
      +materialized: table
      +schema: marts

seeds:
  smard_nuclear:
    +schema: smard

vars:
  nuclear_phaseout_date: "2023-04-15"
  analysis_start_date:   "2022-01-01"
  analysis_end_date:     "2026-12-31"
